### ISSUE TITLE
Colors for bullet charts

### ISSUE THREAD

**Issue by cilyaa** [PMSI-AlignAlytics/dimple#149]
Hi,

I'm having issues with the colors definition for the bullet charts. I'm pretty sure there's an simple solution, but it seems that after scratching my head for a few hours, i can't think clearly anymore...

The bullet charts are directly derived from the example provided, with a few tweaks here and there.

Symptoms: when some values from different measure axes are equal, the color of the first axis is used to display all the other measures with the same value. 
In case i'm not making sense, I've set up a jsfiddle to demonstrate this : http://jsfiddle.net/e7f6t3oc/1/

I'd like to have a color per measure axis, even though the values on the axes are the same. 

Thanks !

**Comment by dizzy0ny** [comment]
I think you can do this by adding unique dummy category for each series being added...so something like this:

    var lm = bullet.addSeries(["Overall","DummyCat1"], dimple.plot.bar, [bY, lX]);
    // Add the main series
    var b = bullet.addSeries(["Participant","DummyCat2"], dimple.plot.bar, [bY, bX]);
    // Add the comparison series
    var m = bullet.addSeries(["Customer","DummyCat3"], dimple.plot.bar, [bY, cX]);
    var g = bullet.addSeries(["Supplier","DummyCat4"], dimple.plot.bubble, [bY, gX]);

**Comment by cilyaa** [comment]
Hi,

that's exactly it ! It works like a charm :+1: 

I've updated the fiddle, in case it can help someone in the future : http://jsfiddle.net/e7f6t3oc/5/

I'll have to read the docs and source more meticulously to understand the mechanism behind that though.

Thanks a lot !
