### ISSUE TITLE
Vertical 100% bar: allow values > 100%?

### ISSUE THREAD

**Issue by mcalthrop** [PMSI-AlignAlytics/dimple#153]
Hi

I have a current requirement that uses something like [Vertical 100% Bar](http://dimplejs.org/examples_viewer.html?id=bars_vertical_stacked_100pct), but allows for ratios to be greater than 100%.

Initially, this seems silly: why have a figure greater than 100%?

The context is this:
- each vertical bar represents a quota
- the bar is divided into *Used* and *Unused* parts of the quota, which should total the full amount of the quota
- however, it is possible for someone to have used more than the quota assigned to them, in which case, the requirement is to indicate this visually by providing a bar that goes beyond the 100% mark

Any ideas on how to implement this?

many thanks in advance

Matt

**Comment by johnkiernander** [comment]
That's fine but it's not what the 100% chart is for.  You just need to create a standard vertical bar and use your quota percentage on a standard measure axis.  If you set `y.tickFormat = "%"` it will format them as percentages and appear exactly the same as the 100% chart (but without the 100% cap).

**Comment by mcalthrop** [comment]
Ok, thanks for the quick reply John!

One further requirement then: 
- am currently setting the colours via `chart.defaultColors`
- and adding an order rule via `series.addOrderRule()`
- but I need to be able to set the colour of the *Used* section of the bar to a given colour in certain circumstances (amber when 95% < used/total < 100%; red when used/total >= 100%)

How would I do this?

Matt

**Comment by johnkiernander** [comment]
You will need to add those bandings into your data. e.g.

    data.forEach(function (d) {
        if (d["Quota Pct"] < 0.95) {
            d["Band"] = "Under Quota";
        } else if (d["Quota Pct"] < 1) {
            d["Band"] = "On Quota";
        } else {
            d["Band"] = "Over Quota";
        }
    });

Then you can assign colours like this (assuming "used/unused" is the name of the dimension to stack by):

    // The last element in the series array is used for colouring
    myChart.addSeries(["Used/Unused", "Band"], dimple.plot.bar);
    // You can assign particular colours to any value of this dimension using the assignColor method
    myChart.assignColor("Under Quota", "amber");
    myChart.assignColor("On Quota", "green");
    myChart.assignColor("Over Quota", "red");

There's more about assignColor here: https://github.com/PMSI-AlignAlytics/dimple/wiki/dimple.chart#assignColor

**Comment by mcalthrop** [comment]
Fantastic. Really appreciate your detailed response John.

**Comment by mcalthrop** [comment]
Closing issue; have a solution. Thanks again John.
