### ISSUE TITLE
`addPctAxis` crashes when all series are zero.

### ISSUE THREAD

**Issue by artsyca** [PMSI-AlignAlytics/dimple#158]
Steps to reproduce:
- Exact same example as http://dimplejs.org/examples_viewer.html?id=areas_horizontal_stacked_100pct
- However, all series have 0 at the same time for single category.
- Charts will not draw at all.

Expected behaviour:

While this is an edge case, it shouldn't cause a catastrophic failure. perhaps when the total sum is zero, leave a gap in the chart?

**Comment by timbtlr** [comment]
+1 I am seeing the same breaking issue for 100pct area charts.

**Comment by timbtlr** [comment]
@artsyca Was this resolved or are you just closing the issue?

**Comment by artsyca** [comment]
Just closing the issue.
