### ISSUE TITLE
How to rotate x-axis label text?

### ISSUE THREAD

**Issue by mcalthrop** [PMSI-AlignAlytics/dimple#159]
Hi

I'm building a [Vertical bar](http://dimplejs.org/examples_viewer.html?id=bars_vertical) chart.

The text for the labels on the x-axis are taking up a lot of room, so I'd like to swing them to the right a bit – maybe by 45 degrees or so.

Is there a way of doing this with dimplejs, or do I need to resort to hackery? ([like this](http://stackoverflow.com/a/17792468/155206), for example).

Matt

**Comment by mcalthrop** [comment]
Bump!

**Comment by johnkiernander** [comment]
That is the best way at the moment.  It would nice to have more control through the API.

**Comment by mcalthrop** [comment]
Ok, thanks John.

**Comment by mcalthrop** [comment]
FWIW, I ended up with a fairly simple solution, based on your SO solution above:

* assume that if there is already a value for the `transform` attribute, it has been set by `dimple` in order to make the label vertical instead of horizontal
* in which case, it will look something like this: `rotate(90,37.5,12.1015625) translate(-5, 0)`
* which means that all we have to do is change the angle from 90 to 45

Sample code snippet, after calling `chart.draw()`:
``` javascript
xAxis.shapes.selectAll('text').attr('transform',
    function () {
        var transformAttributeValue = d3.select(this).attr('transform');
        
        if (transformAttributeValue) {
            transformAttributeValue = transformAttributeValue.replace('rotate(90,', 'rotate(45,');
        }

        return transformAttributeValue;
);
```
