### ISSUE TITLE
Drawing line between coordinates

### ISSUE THREAD

**Issue by dt1973** [PMSI-AlignAlytics/dimple#160]
Based on http://jsbin.com/wiviwoqeji/1/edit - how would one go about drawing a line between the coordinates to illustrate it's a triangle?

**Comment by johnkiernander** [comment]
You can use an area chart: 
http://jsbin.com/jegedeyiki/2

Does that work for you?

**Comment by dt1973** [comment]
Absolutely! Thank you very much!
