### ISSUE TITLE
No HTTPS protocol to request dimple

### ISSUE THREAD

**Issue by crclayton** [PMSI-AlignAlytics/dimple#200]
In the past I have included the dimple.js with the following tag.

`<script src="http://dimplejs.org/dist/dimple.v2.1.6.min.js"></script>` 

However, recently I've been getting the error:

> **Mixed Content:** The page at '...' was loaded over HTTPS, but requested an insecure script 'http://dimplejs.org/dist/dimple.v2.1.6.min.js'. This request has been blocked; the content must be served over HTTPS.

And I haven't been able to find an HTTPS server to load this library from. Can we get an HTTPS protocol for dimple?

**Comment by johnkiernander** [comment]
I wouldn't generally recommend accessing the library that way. It's fine for trying out dimple but if you are using it in a published site it would be better to either add it to your server and reference it from there or to use a cdn reference (https://cdnjs.cloudflare.com/ajax/libs/dimple/2.1.6/dimple.latest.min.js).

**Comment by crclayton** [comment]
That's how it says to include it on the front page [here](http://dimplejs.org/). That `cdnjs.cloudflare` link you added works though, you might want to update the front page to use that just so first time users don't get hung up on that. Thanks for your prompt response!
