### ISSUE TITLE
Null values on a line chart

### ISSUE THREAD

**Issue by fair-plate** [PMSI-AlignAlytics/dimple#22]
If there is a null value (on purpose) how should this be handled in teh chart?

Currently I think it won't plot any of the other values so its empty.

**Comment by dizzy0ny** [comment]
i agree with sarcidiacono.  Infact, i think there should be an option that allows you to decide how you want nulls to be treated.  Right now i'm looking for a way to print dates on the x-axis, but no value.  the use case im struggling with is that a  page has two charts, and i want the dates of the two to be the same..even if no data exist for one of the time-series.

**Comment by RichardNeill** [comment]
I have a suggestion - at least for a bar chart. Let's say we've measured 50 different branches, and got a score for each of them. Some branches scored 0.  One branch didn't return their data. So... how can we represent the latter?  We could remove the bar entirely, but I think there is a case for explicitly drawing a representation of "this branch failed to submit a value".

At the moment, dimple does the "least surprise" approach and treats the null as a zero when drawing the bar height.

I suggest re-formatting the bar label (probably as a strikethrough), and adding the word "NULL" into the tooltip where it currently shows the value of 0. Is there a neat way to do this?

**Comment by RichardNeill** [comment]
With a bar chart, a zero-height bar is at least invisible. But with a bubble, the bubble is now shown as zero. Worse, the tool-tip shows that the value is "0", when it should actually say "null".
