### ISSUE TITLE
Question about Text inside pieCharts

### ISSUE THREAD

**Issue by DavidStrada** [PMSI-AlignAlytics/dimple#232]
Hey, I have a question about what would be the ideal way of inserting or achieving the following : 

![screen shot 2016-05-22 at 1 52 28 pm](https://cloud.githubusercontent.com/assets/413631/15456140/d05632f2-2024-11e6-9e42-320e2f3383dc.png)

I have tried to implement it but not sure about how good/bad it's, base on your experience how would you doit ? 

here's the link to. [Implementation Attempt](http://jsbin.com/ravahipiye/1/edit?js,output)

Thanks,

**Comment by johnkiernander** [comment]
The general approach you've used for adding the text is fine.  I've adjusted your code to center it in a more flexible way.  The key changes are adding:

    .style("text-anchor", "middle")

to horizontally center text and:

    .attr("dy", "0.35em")

which vertically centres the text.

Here's the updated bin:

http://jsbin.com/digegec/1/edit?js,output

**Comment by DavidStrada** [comment]
Thanks! appreciated, what’s the logic of that dy : 0.35em “curious about it”
