### ISSUE TITLE
Can it work with D3 V4?

### ISSUE THREAD

**Issue by stephaniep-topdesk** [PMSI-AlignAlytics/dimple#235]
If I use the example from the dimplejs.org page, I get:

TypeError: d3.scale is undefined
	this._scale = d3.scale.ordinal()

when using the latest d3 version. Will it be updated or should we continue to use v3?

**Comment by johnkiernander** [comment]
The latest version of Dimple only supports V3.  I'll release a V4 compatible library as soon as I can.

**Comment by stephaniep-topdesk** [comment]
Good to know! Thanks for the quick response! :)

**Comment by jfsiii** [comment]
@johnkiernander Is there a branch/ticket/milestone/etc people can track?
