### ISSUE TITLE
EventHandler doesn't work for dimple.plot.line

### ISSUE THREAD

**Issue by LouisGi** [PMSI-AlignAlytics/dimple#75]
I'm checking the downloaded examples and I try to add the handler :       s.addEventHandler("click", function (e) {
          alert("Hey, you clicked . Woooooo!");
      });
On the example lines_horizontal_grouped.html

If I just change the series from dimple.plot.line to dimple.plot.bubble it works nicely!

**Comment by ppsingh-ic** [comment]
is this issue fixed , please update the fix or version ..
